//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smart_Shop.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerProduct
    {
        public int Id { get; set; }
        public int CusId { get; set; }
        public int ProdId { get; set; }
        public System.DateTime Date { get; set; }
        public int Quantity { get; set; }
        public int Status { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Product Product { get; set; }
    }
}
